### 첫 질문 생성
GET localhost:8080/api/initial

### 이후의 대화
GET localhost:8080/api/chat?prompt=안녕하세요. 우선 첫 질문을 드리겠습니다. 운영체제는 무엇인가요? 운영체제는 OS입니다.
    좋습니다. 그럼 다음 질문입니다. 운영체제의 주요 기능에는 어떤 것들이 있나요? CPU 스케줄링이 있습니다.


